name: Build and Test SVTECH App

on:
  push:
    branches: [ $default-branch ]
  pull_request:
    branches: [ $default-branch ]

env:
  # Modify your image and container here
  IMAGE_TAG: 'v1.${{ github.run_number }}' # This will be used as package version
  IMAGE_NAME: 'your-image-name'
  CONTAINER_NAME: 'your-container-name'
  CONTAINER_MAPPING_PORT: '80:80'

jobs:  
  build:
    runs-on: ubuntu-dind
    permissions:
      contents: read
      packages: write
    steps:
    - name: Checkout code
      uses: actions/checkout@v4

    - name: Set up Docker Buildx
      uses: docker/setup-buildx-action@v3

    - name: Build image
      run: |
        docker buildx build --platform linux/amd64 \
          --cache-from=type=registry,ref=ghcr.io/${{ env.REPO }}:cache \
          --load \
          --tag ghcr.io/${{ env.REPO }}:${{ env.IMAGE_TAG }} .

    - id: run_and_check_container_status
      name: Run App
      uses: svtechnmaa/.github/actions/run_docker_container@main
      with:
        imageName: '${{ env.IMAGE_NAME }}'
        containerName: '${{ env.CONTAINER_NAME }}'
        containerMappingPort: '${{ env.CONTAINER_MAPPING_PORT }}'

    - name: Downcase REPO
      run: |
        echo "REPO=${GITHUB_REPOSITORY,,}" >>${GITHUB_ENV}

    - name: Login to GitHub Container Registry
      uses: docker/login-action@v2
      with:
        registry: ghcr.io
        username: '${{ github.repository_owner }}'
        password: '${{ secrets.GITHUB_TOKEN }}'
        
    - name: Build and push image to ghcr.io
      run: |
        docker buildx build --platform linux/amd64 \
          --cache-from=type=registry,ref=ghcr.io/${{ env.REPO }}:cache \
          --cache-to=type=registry,ref=ghcr.io/${{ env.REPO }}:cache,mode=max \
          --push \
          --tag ghcr.io/${{ env.REPO }}:${{ env.IMAGE_TAG }} . 

  test: 
    needs: build
    runs-on: robot-dind
    permissions:
      contents: read
      packages: write
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Downcase REPO
        run: |
          echo "REPO=${GITHUB_REPOSITORY,,}" >>${GITHUB_ENV}

      - name: Login to GitHub Container Registry
        uses: docker/login-action@v2
        with:
          registry: ghcr.io
          username: '${{ github.repository_owner }}'
          password: '${{ secrets.GITHUB_TOKEN }}'
          
      - name: Pull image from GitHub Container Registry
        run: |
          docker pull ghcr.io/${{ env.REPO }}:${{ env.IMAGE_TAG }}

      - id: run_and_check_container_status
        name: Run App
        uses: svtechnmaa/.github/actions/run_docker_container@main
        with:
          imageName: 'ghcr.io/${{ env.REPO }}:${{ env.IMAGE_TAG }}'
          containerName: '${{ env.CONTAINER_NAME }}'
          containerMappingPort: '${{ env.CONTAINER_MAPPING_PORT }}'
          
      - name: Run Robot Framework tests
        run: |
          echo "##[command]robot tests/"
          robot tests/

      - name: Delete package from GHCR if test fails
        if: failure() 
        run: |
          echo "Robot test failed, deleting package from GHCR..."
          REPO_NAME=$(echo ${{ env.REPO }} | cut -d'/' -f2)
          echo "Repo name: $REPO_NAME"
          VERSION_ID=$(curl -H "Authorization: Bearer ${{ secrets.GITHUB_TOKEN }}" "https://api.github.com/users/${{ github.repository_owner }}/packages/container/$REPO_NAME/versions" | jq -r '.[] | select(.metadata.container.tags[] == "${{ env.IMAGE_TAG }}") | .id')
          echo "Package version ID: $VERSION_ID"
          curl -i -X DELETE -H 'Authorization: Bearer ${{ secrets.GITHUB_TOKEN }}' -H "Accept: application/vnd.github.v3+json" "https://api.github.com/users/${{ github.repository_owner }}/packages/container/$REPO_NAME/versions/$VERSION_ID"
        
      - name: 'Upload Artifact'
        if: always()
        uses: actions/upload-artifact@v4.6.0
        with:
          name: robot-test-result-#${{ github.run_number }}
          path: |
            ./output.xml
            ./log.html
            ./report.html

      - name: Tag latest image and push to GitHub Container Registry
        if: success()
        run: |
          docker buildx imagetools create -t ghcr.io/${{ env.REPO }}:latest ghcr.io/${{ env.REPO }}:${{ env.IMAGE_TAG }}
          docker buildx imagetools inspect ghcr.io/${{ env.REPO }}:${{ env.IMAGE_TAG }}
