name: Dockerfile Scan and Mail
description: Scan Dockerfile using Trivy and send mail if vulnerabilities detected

inputs:
  dockerfile_path:
    description: "Path to the Dockerfile to scan"
    required: false
    default: './Dockerfile'
  mail_username:
    description: "SMTP username for sending email"
    required: true
  mail_password:
    description: "SMTP password for sending email (stored as secret)"
    required: true
  commit_author_name:
    description: "Name of the commit author to include in email"
    required: true
  commit_author_email:
    description: "Email of the commit author to include in email"
    required: true
  commit_id:
    description: "Git commit ID associated with this scan"
    required: true
  job_id:
    description: "GitHub job ID for the current workflow run"
    required: true


runs:
  using: "composite"
  steps:

    - name: Scan Dockerfile
      id: scan_dockerfile
      shell: bash
      run: |
        echo "Scanning Dockerfile..."
        # Scan Dockerfile, export SARIF
        trivy config --severity HIGH,CRITICAL --format sarif --output trivy-report.sarif ${{ inputs.dockerfile_path }}

        # Generate text summary for log
        jq -r '.runs[].results[] | "\(.ruleId): \(.level)"' trivy-report.sarif > dockerfile_scanning_result.txt

        # Count HIGH + CRITICAL
        HIGH_COUNT=$(jq '[.runs[].results[] | select(.level=="high")] | length' trivy-report.sarif)
        CRITICAL_COUNT=$(jq '[.runs[].results[] | select(.level=="critical")] | length' trivy-report.sarif)
        TOTAL_VULNS=$((HIGH_COUNT + CRITICAL_COUNT))

        echo "HIGH vulnerabilities: $HIGH_COUNT"
        echo "CRITICAL vulnerabilities: $CRITICAL_COUNT"
        echo "TOTAL vulnerabilities: $TOTAL_VULNS"

        # Set output to trigger mail
        if [ "$TOTAL_VULNS" -gt 0 ]; then
          echo "detected_vulns=true" >> $GITHUB_OUTPUT
        else
          echo "detected_vulns=false" >> $GITHUB_OUTPUT
        fi
      continue-on-error: true

    - name: Show results for Dockerfile scanning
      shell: bash
      run: |
        echo "##[command] Show results for Dockerfile scanning"
        cat dockerfile_scanning_result.txt
      continue-on-error: true

    - name: Upload SARIF to Security tab
      uses: github/codeql-action/upload-sarif@v2
      with:
        sarif_file: trivy-report.sarif
      continue-on-error: true

    - name: Send mail if vulnerabilities detected
      if: steps.scan_dockerfile.outputs.detected_vulns == 'true'
      uses: dawidd6/action-send-mail@v4
      with:
        server_address: smtp.gmail.com
        server_port: 465
        secure: true
        username: ${{ inputs.mail_username }}
        password: ${{ inputs.mail_password }}
        subject: "[ALERT] Vulnerabilities Found in Dockerfile"
        body: |
          Hello ${{ inputs.commit_author_name }},

          Detected vulnerabilities for commit:
          ${{ github.server_url }}/${{ github.repository }}/commit/${{ inputs.commit_id }}

          View the full report here:
          ${{ github.server_url }}/${{ github.repository }}/actions/runs/${{ github.run_id }}/job/${ inputs.job_id }

          Please review the details and take appropriate action.

          Best,
          SRE Team
        to: ${{ inputs.commit_author_email }}
        from: kien.kim@svtech.com.vn
      continue-on-error: true
