name: Weekly Org Trivy Scan

on:
  push:
    branches:
      - main
      - feat/*
  workflow_dispatch:
#   schedule:
#     - cron: "17 2 * * 6"

permissions:
  contents: read
  security-events: write

env:
  ORG_NAME: svtechnmaa
  GH_TOKEN: ${{ github.token }}


jobs:
   schedule-scan:
    runs-on: ubuntu-dind
    steps:          
        - name: Get all repositories in the organization
          id: get_repos
          
          run: |
            echo "Fetching repositories for organization: ${{ env.ORG_NAME }}"
            echo "$${{ env.GH_TOKEN }}" | gh auth login --with-token" 
            repos=$(gh repo list ${{ env.ORG_NAME }} --json name -q '.[].name')
            echo "Repositories: $repos"
            echo "REPOS=$repos" >> $GITHUB_ENV
        
        - name: Test out check output 
          run: |
            echo "Repositories: ${{ env.REPOS }}"